#server.address=0.0.0.0
#server.port=9081
#
#
#spring.datasource.url=jdbc:mysql://10.191.27.110:3306/sakila?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=team27
#spring.datasource.password=1234
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
#
#spring.jpa.hibernate.ddl-auto=none
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp



server.port=9080
spring.datasource.url=jdbc:mysql://localhost:3306/sakila?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Biswajit@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
